version: "3.9"

services:

  app:
    build: .
    container_name: ecommerce_app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    env_file:
      - .env
    restart: always

  mongo:
    image: mongo:7
    container_name: ecommerce_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data: